"""empty message

Revision ID: c3494067301b
Revises: 
Create Date: 2020-02-10 23:08:51.124542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3494067301b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Drink', sa.Column('tagline', sa.String(length=180), nullable=False))
    op.drop_column('Drink', 'price')
    op.drop_column('Drink', 'recipe')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Drink', sa.Column('recipe', sa.VARCHAR(length=180), autoincrement=False, nullable=False))
    op.add_column('Drink', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('Drink', 'tagline')
    # ### end Alembic commands ###
