"""empty message

Revision ID: ec67e8b3affe
Revises: 
Create Date: 2020-02-10 08:41:05.140702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec67e8b3affe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drink')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drink',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('recipe', sa.VARCHAR(length=180), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='drink_pkey'),
    sa.UniqueConstraint('title', name='drink_title_key')
    )
    # ### end Alembic commands ###
